#版本号
version: "3"
#服务
services:
  #hgoj服务
  hgoj:
    #服务器镜像
    build:
      context: ./hgoj
      dockerfile: Dockerfile
#    image: registry.cn-zhangjiakou.aliyuncs.com/hgoj/hgoj:v1.1
    container_name: hgoj_server
    depends_on:
      - mysql
    restart: always
    volumes:
      - ${JUDGE_DATA}:/home/judge/data
      - ${HGOJ_CONF}/app.conf:/data/www/hgoj/conf/app.conf
      - ${HGOJ_LOG}:/data/www/hgoj/logs
    # 端口映射。前者是宿主的。后者是容器里端口
    ports:
      - "8086:8086"

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: hgoj_mysql
    volumes:
      - ${DATA_PATH_HOST}/mysql${MYSQL_VERSION}:/var/lib/mysql
      - ${LOG_PATH_HOST}/mysql${MYSQL_VERSION}:/var/log/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}

  judge:
#    build:
#      context: ./judge
#      dockerfile: Dockerfile
    image: registry.cn-zhangjiakou.aliyuncs.com/hgoj/judge:v1
    container_name: hgoj_judge
    depends_on:
      - mysql
    volumes:
      - ${JUDGE_DATA}:/home/judge/data
      - ${JUDGE_CONF}/judge.conf:/home/judge/etc/judge.conf
      - ${JUDGE_CONF}/java0.policy:/home/judge/etc/java0.policy
    restart: always
    
  nginx:
    image: registry.cn-zhangjiakou.aliyuncs.com/hgoj/nginx:v1
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
    container_name: hgoj_nginx
    depends_on:
      - hgoj
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
      - ${LOG_PATH_HOST}/nginx:/var/log/nginx
    ports:
      - "80:80"
    restart: always

  phpmyadmin:
    image: registry.cn-zhangjiakou.aliyuncs.com/hgoj/phpmyadmin:v1
    container_name: hgoj_phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
    ports:
      - "8080:80"
  redis:
    image: registry.cn-zhangjiakou.aliyuncs.com/hgoj/redis:v1
    container_name: hgoj_redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "6379:6379"
    restart: always
